testng_homeWork
razerved/AutpmationAQA pull request #1
Opened 2023-06-24 16:51 UTC by razerved

Знаю, что мог все обьеденить и сделать Красиво в StaticProvider, но мне надо так.

2023-06-26 12:35 UTC, wildpioneer requested changes

2023-06-26 12:35 UTC, wildpioneer commented on src/test/java/HomeWorkTest.java
> +    @Test(testName = "Деление на 0 double")
Хочу еще видеть тесты деления на положительный и отрицательный 0.0

2023-06-26 12:35 UTC, wildpioneer commented on src/test/java/HomeWorkTest.java
> +
Сразу начинай обращать внимание на форматирование

2023-06-26 12:35 UTC, wildpioneer commented on src/main/java/Calculator.java
> +    public int homeMines(int a, int b){
В задании ничего не говорилось о данном методе - для чего ты его сделал?

2023-06-26 16:04 UTC, razerved commented on src/main/java/Calculator.java
> +    public int homeMines(int a, int b){
честно не помню для чего его сделал, наверно в момент пока писал код в месте с тобой сразу сделал на сложение и вычитание

2023-06-26 16:14 UTC, razerved commented on src/main/java/Calculator.java
> +    public int homeMines(int a, int b){
Наверно автоматом написал, не помню..
типа как pojo делается)

2023-06-26 16:17 UTC, razerved commented on src/test/java/HomeWorkTest.java
> +    @Test(testName = "Деление на 0 double")
Да, такие же тесты только с Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY

2023-07-03 20:17 UTC, wildpioneer commented
Проверено - переделывать Иван не планирует по договоренности

2023-07-03 20:17 UTC, closed without merging