locators_homeWork
razerved/AutpmationAQA pull request #3
Opened 2023-07-15 19:02 UTC by razerved

Вроде все главное зацепил, кроме базового text(),

2023-07-15 19:10 UTC, razerved commented
Да, забыл по поводу LogInAndClickAddProject(). Знаю что можно было обыграть вынести и т.д. ( сделал как сделал, на скорую руку )

2023-07-17 08:46 UTC, wildpioneer requested changes

2023-07-17 08:46 UTC, wildpioneer commented on src/test/java/HomeWork.java
> +        assertTrue(driver.findElement(By.cssSelector("[name='suite_mode']:checked")).isDisplayed());
Это явно не весь набор рассмотренный на занятии

2023-07-17 15:55 UTC, razerved commented on src/test/java/HomeWork.java
> +        assertTrue(driver.findElement(By.cssSelector("[name='suite_mode']:checked")).isDisplayed());
Верно, пропустил пару, но их ведь и не 4 шт)
с 44 по 52
checked, enabled, disabled, empty - по нужде и типу
*|=lord ( к примеру) часто сбоит, по буквенный лучше
child (first\last)- такое
:nth-of-type кстати вроде еще юзают активно.

2023-07-23 12:59 UTC, wildpioneer commented
Проверено

2023-07-23 12:59 UTC, closed without merging