Page object home work
razerved/AutpmationAQA pull request #7
Opened 2023-07-20 23:18 UTC by razerved

=(

2023-07-21 20:54 UTC, razerved commented
Вчера накокодил без сил, так сказать.
BaseStep это точка входа(предполагалась для всех Page, что бы Steps не городить), не стал со всех страниц дергать методы в него ( по типу LoginPage ) 
в каждом классе составил метод который возвращает следующую стр. Если есть необходимость, что бы меньше 8 не получить могу все методы вынести..

2023-07-23 12:29 UTC, wildpioneer commented
Так а e2e тест где?

2023-07-23 12:32 UTC, wildpioneer commented
Структуру лучше всего конечно исправлять - потому что разобраться затем во всем этом требует времени

2023-07-23 12:53 UTC, wildpioneer commented
И самое главное - нам надо договориться о глубине проверки - так как ты работу делаешь поверхностно из-за нехватки времени с понимаем того, что ты это знаешь - то насколько важно тебе в таких случаях детальная проверка?

2023-07-23 12:53 UTC, wildpioneer requested changes

2023-07-23 12:53 UTC, wildpioneer commented on src/test/java/homeWork/tests/TestHW.java
> +                .clickBackHomeButton();
Так а проверка собственно где?

2023-07-23 12:53 UTC, wildpioneer commented on src/test/java/homeWork/Page/BascetPageHW.java
> +    private final String path = "https://www.saucedemo.com/inventory.html";
Путь к странице должен быть относительным - я так понимаю тут ты просто не захотел исправлять config?

2023-09-04 12:55 UTC, wildpioneer commented
Проверено

2023-09-04 12:55 UTC, closed without merging