Домашняя работа AdvancedAction
razerved/AutpmationAQA pull request #8
Opened 2023-07-22 22:12 UTC by razerved

А мне понравился пунк про скачку файла!
Видел другую реализацию, сам нормально не сталкивался с такой чтукой.

2023-07-23 13:08 UTC, wildpioneer requested changes

2023-07-23 13:08 UTC, wildpioneer commented on src/test/java/homeWork/TestHW.java
> +        String pathToFile = ActionTest.class.getClassLoader().getResource("deadpoll2.jpg").getPath()
1. Отсутствует проверка на систему - и соответственно у меня не работает
2. А почему ActionTest.class - если ты в TestHW.class

2023-07-23 13:08 UTC, wildpioneer commented on src/test/java/homeWork/TestHW.java
> +        File folder = new File(System.getProperty("user.dir"));
Отсутствует ожидание скачивания файла. Ты его пытаешся проверить - весьма грамоздким методом - но ты его не дожидаешся

2023-07-23 13:08 UTC, wildpioneer commented on src/test/java/homeWork/TestHW.java
> +        for (File listOfFile : listOfFiles) {
Вариант попроще:
private static void waitForFileDownload(String folderPath, String fileName) {
        // Устанавливаем максимальное время ожидания скачивания файла
        int maxWaitSeconds = 60;
        int elapsedSeconds = 0;
        File fileToCheck = new File(Paths.get(folderPath, fileName).toString());

        while (!fileToCheck.exists() && elapsedSeconds < maxWaitSeconds) {
            try {
                TimeUnit.SECONDS.sleep(1);
                elapsedSeconds++;
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

        if (fileToCheck.exists()) {
            System.out.println("Файл скачался успешно!");
        } else {
            System.out.println("Файл не был скачан за отведенное время.");
        }
    }

2023-07-23 19:45 UTC, razerved commented on src/test/java/homeWork/TestHW.java
> +        String pathToFile = ActionTest.class.getClassLoader().getResource("deadpoll2.jpg").getPath()
Обновил, должно работать.

2023-07-23 19:45 UTC, razerved commented on src/test/java/homeWork/TestHW.java
> +        for (File listOfFile : listOfFiles) {
Шикарноо!!!!
Заюзал, добавил новым тестом!

2023-07-23 19:45 UTC, razerved commented
Обнова

2023-08-14 08:52 UTC, wildpioneer commented
Проверено

2023-08-14 08:52 UTC, closed without merging